# 실습 WEEK11: Pandas I

:::{admonition} 안내
:class: info

- 실습 문제는 사전, 도전, 완전 실습 문제로 구성되어 있습니다.
- 사전 실습 문제는 수업 전에 미리 풀어보시면 도움이 됩니다.
- **<font color='blue'>도전 실습 문제는 문제의 소스코드를 작성하여 결과가 정확하게 나오면 etl>모듈>과제>에 제출하여야 과제 점수를 받을 수 있습니다.</font>**
- **<font color='red'>제출기한은 etl>모듈>과제에 설정된 기한을 확인하여 주시기 바랍니다.(일반적으로 수업당일 자정까지)</font>**
- 완전 실습 문제는 보너스 실습 문제로 생각하시면 됩니다.  도전 실습 문제를 다 풀어본 학생들이 추가적으로 풀어보시면 도움이 됩니다.
- 사전 실습 문제와 완전 실습 문제는 수업 시간에 별도 풀이를 하지 않습니다.
- 질문은 사전, 도전, 완전 그리고 수업과 관련된 모든 것에  대하여 교수자 or 조교 or 튜터에게 하시면 됩니다.
- **<font color='red'>가독성을 위해 입출력 데이터에서 콜론(:) 다음에는 항상 한칸 공백이 있습니다.</font>**

:::

# [도전 실습 문제]

## Problem:(함께+스스로) Gapminder 데이터 활용해보기
- Gapminder 데이터에는 유엔의 데이터를 바탕으로 5개 대륙, 총 142개 국가에 대한 인구 데이터 등이 5년 간격으로 담겨있다.
- 이 데이터를 통해 인구 예측, 부의 이동 등 특정 국가(군)별, 대륙별, 소득수준별 변화동향을 파악할 수 있다.

- 아래 사이트에서 gapminder.tsv파일을 코랩에서 불러와보자.

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/HaesunByun/common/main/data/gapminder.tsv",sep="\t")
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

😄 .shape으로 데이터프레임 모양 확인하기

😄 .head()로 5개 행 데이터 확인하기

😄 .info()로 데이터의 전반적인 정보 확인하기

#### 데이터 추출방법

- 데이터프레임명.iloc[]로 추출
```
데이터프레임명.iloc[행 또는 행범위, 열 또는 열범위]
```
- 데이터프레임명.loc[]로 추출
```
데이터프레임명.loc[행 또는 행범위, 열 또는 열범위]
```
- 데이터프레임명으로 추출
```
데이터프레임명[행범위][열이름 또는 열이름 리스트]
데이터프레임명[열이름 또는 열이름 리스트][행범위]
```

### (함께) country열 추출하기

### (스스로)country, continent, year 열 추출하기
- 여러개의 열을 추출할때에는 리스트로 열의 이름을 적어준다.

### (함께)칼럼 country가 Afghanistan인 값들을 추출하기

### (스스로)인덱스 7~10행 데이터 중에서 country, lifeExp, gdpPercap 열의 데이터만 추출하기

## Problem:(함께+스스로) 데이터프레임 생성하여 조건에 맞는 데이터 찾아보기

### (스스로) 데이터프레임 생성하기
- 아래 데이터를 이름, 성별, 나이, 직업을 key로 하는 딕셔너리를 만들고 이 key를 열로 갖는 데이터프레임을 만들어보세요.

```
김철수	남	60	전문직
김미영	여	62	기타
이수지	여	20	학생
홍길동	남	32	직장인
이철	남	45	자영업
```
<div align="center"><img src="https://haesunbyun.github.io/common/images/pd1.PNG" width="300"></div>

- 위에서 생성한 데이터프레임에서 조건에 맞는 데이터를 찾아보세요.

### (스스로)여성고객 추출하기

### (함께)나이가 60 이상인 여성 고객 명단 추출하기
- 여러개의 조건을 나열할 때에는 & 기호로 조건을 연결합니다.

### (스스로)30, 40대 고객 명단 추출하기

### (함께)나이가 많은 사람부터 적은 사람 순서로 정렬하기

### (스스로)이름 순서로 정렬하기

## Problem:(스스로+함께) BMI 지수와 비만도 결정

### Problem:(스스로) BMI 지수 계산하기
😄 주어진 링크를 통해 데이터를 데이터프레임으로 가져와 주세요.

https://raw.githubusercontent.com/HaesunByun/common/main/data/Height_Weight_Index.csv

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/HaesunByun/common/main/data/Height_Weight_Index.csv')

😄 .shape으로 데이터프레임 모양 확인하기

😄 .head()로 5개 행 데이터 확인하기

😄 .info()로 데이터의 전반적인 정보 확인하기

😄 BMI 지수를 나타내는 "BMI" 열을 만드시오. BMI 지수는 다음과 같이 계산할 수 있습니다.
```
BMI = 체중(kg) ÷ {신장(m) × 신장(m)}
```

😄 남자 BMI 평균, 여자 BMI 평균을 출력하시오

---
Output Sample
```
남자 BMI 평균: 38.15
여자 BMI 평균: 37.39
```

### Problem:(함께) 비만도 결정

BMI 지수에 따라 다음과 같이 비만도를 결정할 수 있습니다.
```
저체중 : BMI 18.5 이하
정상 : BMI 18.5 초과 23 이하
과체중 : BMI 23 초과 25 이하
비만 : BMI 25 초과
```

😄 비만도를 나타내는 "obesity" 열을 위의 조건에 맞게 만드시오.

😄 성별과 비만도에 따른 사람의 수를 count하여 출력해보시오.

Hint : groupby 사용하기

---
DataFrame Sample
```
Gender	Height	Weight	bmi
0	Male	174	96	31.708284
1	Male	189	87	24.355421
2	Female	185	110	32.140248
3	Female	195	104	27.350427
```
Output Sample
```
Gender  obesity
Female  과체중         11
        비만          204
        저체중         13
        정상           27
Male    과체중          8
        비만          196
        저체중         21
        정상           20
```

Gender  obesity
Female  과체중         11
        비만         204
        저체중         13
        정상          27
Male    과체중          8
        비만         196
        저체중         21
        정상          20
dtype: int64

# [완전 실습 문제]

## Problem: 월별 교통사고 분석

### Problem: 월별 교통사고 사상자수 구하기
😄 주어진 링크를 통해 아래와 같은 데이터프레임을 가져와 주세요.<br>

url: https://raw.githubusercontent.com/HaesunByun/common/main/data/drowsydriving.csv

```
  구분   승용차 사고 사망 부상
201401 16561665  169   7   347
201402 16626372  145   3   268
201403 16691079  206  12   358
             ...
 ```

😄 '사상자수'를 나타내는 칼럼을 새롭게 추가하세요.
'사상자수'는 아래와 같은 공식을 통해 계산됩니다.
```
사상자수 = 사망(명) + 부상(명)
 ```

output sample
```
  구분   승용차 사고 사망 부상 사상자수
201402 16626372  145   3   268     271
201602 18179420  174   6   328     334
201412 17273442  178  12   329     341
            ...
 ```

😄 '사상자수'의 최댓값&최솟값을 출력하고 사상자수를 기준으로 오름차순 정렬한 결과를 5개의 행만 출력해보세요.

output sample
```
최대 사상자수: 563명
최소 사상자수: 271명
```

### Problem: 월별 교통사고 위험지수 구하기
😄 월별 '위험지수'을 나타내는 칼럼을 새롭게 추가해주세요.

'위험지수'은 아래와 같은 공식을 통해 계산됩니다.
```
위험지수 = 10000 * ( 사고(건) + 20 * 사망(명) + 2 * 부상(명) ) / 승용차(대)
 ```
그리고 위험지수의 최댓값과 최솟값을 출력하고,
데이터프레임을 '위험지수' 칼럼을 기준으로 내림차순 정렬하세요.

output sample
```
최대 위험지수: 0.9645
최소 위험지수: 0.4457

  구분   승용차 사고 사망 부상 사상자수  위험지수
201508 17791145  268  19   534     553   0.964525
201405 16820493  218  17   474     491   0.895336
201507 17726433  273   7   556     563   0.860297
            ...
 ```